/**
 * MP_ITEM and MP_MAINTENANCE feed payload schemas, one per marketplace. Wire
 * types: as long as Walmart made them.
 *
 * `MpItem*` is the US/consumer schema, `MpItemCA*` the Canadian one and
 * `MpItemIntl*` the international variant — they are separate schemas rather
 * than one with optional members, which is how Walmart publishes them.
 */
export interface MpItemFeed {
  MPItemFeedHeader: WalmartFeedHeader;
  MPItem: MpItem[];
}

interface WalmartFeedHeader {
  locale: "en";
  version: string;
  businessUnit: "SAMSCLUB" | "WALMART_CA" | "WALMART_US" | "ASDA_GM";
  // These are in walmart docs but uneeded for our processes
  processMode?: "Merge" | "Replace";
  requestBatchId?: string;
  requestId?: string;
  sellingChannel?: string;
  subCategory?: string;
  subset?: string;
}

export type ItemFeedType = "MP_ITEM" | "MP_MAINTENANCE";

export interface MpItem {
  Orderable: WalmartUSOrderable | WalmartCAOrderable;
  /** there will only be one key value pair in the Visible key */
  Visible: Record<string, WalmartFullVisible>;
}

// --- Walmart Canada MP_MAINTENANCE types ---
// The CA MP_MAINTENANCE Orderable differs from the US one:
// - ShippingWeight is an object { measure, unit } not a plain number
// - specProductType and country_of_origin_substantial_transformation are absent
// - Content fields (productName, brand, keyFeatures, etc.) live in Orderable, not just Visible

interface WalmartCAMaintenanceFeedHeader {
  processMode: "REPLACE";
  subset: "EXTERNAL";
  sellingChannel: "mpmaintenance";
  mart: "WALMART_CA";
  version: string;
  locale: string[];
}

export interface MpItemCA {
  Orderable: WalmartCAOrderable;
  Visible: Record<string, WalmartCAVisible>;
}

export interface MpItemCAFeed {
  MPItemFeedHeader: WalmartCAMaintenanceFeedHeader;
  MPItem: MpItemCA[];
}

export interface WalmartCAOrderable {
  sku: string;
  productIdentifiers: WalmartProductIdentifiers;
  price?: number;
  msrp?: number;
  MinimumAdvertisedPrice?: number;
  productTaxCode?: number;
  ShippingWeight?: { measure: number; unit: "lb" };
  productName?: string;
  brand?: string;
  manufacturer?: string;
  manufacturerPartNumber?: string;
  shortDescription?: string;
  mainImageUrl?: string;
  productSecondaryImageURL?: string[];
  keyFeatures?: string[];
  features?: string[];
  warrantyText?: string;
  warrantyURL?: string;
  keywords?: string;
  batteryTechnologyType?: string;
  electronicsIndicator?: "Yes" | "No";
  isChemical?: "Yes" | "No";
  isPesticide?: "Yes" | "No";
  isAerosol?: "Yes" | "No";
  isTemperatureSensitive?: "Yes" | "No";
  MustShipAlone?: "Yes" | "No";
  shipsInOriginalPackaging?: "Yes" | "No";
  startDate?: string;
  endDate?: string;
  hsCode?: string;
  countryOfOriginAssembly?: string[];
  smallPartsWarnings?: string[];
}

interface WalmartProductIdentifiers {
  productId: string;
  productIdType: "UPC" | "EAN" | "ISBN" | "GTIN";
}

interface WalmartExternalProductIdentifier {
  externalProductIdType: "ASIN";
  externalProductId: string;
}

interface WalmartInventory {
  quantity?: number;
  fulfillmentCenterID?: string;
  inventoryAvailabilityDate?: string;
}

interface WalmartStateRestrictions {
  stateRestrictionsText?: "Commercial" | "Illegal for Sale" | "None";
  zipCodes?: string;
  states?: string;
}

interface WalmartAutomatePricing {
  minimumSellerAllowedPrice?: number;
  maximumSellerAllowedPrice?: number;
  repricerStrategy?: string;
}

interface WalmartProductPackageDimensionsAndWeight {
  product_package_dimensions_depth: number;
  product_package_weight: number;
  product_package_dimensions_height: number;
  product_package_dimensions_width: number;
}

interface MeasureAndUnit {
  unit: string;
  measure: number;
}

export interface WalmartUSOrderable {
  sku: string;
  productIdentifiers: WalmartProductIdentifiers;
  price: number;
  country_of_origin_substantial_transformation?: string;
  ShippingWeight?: number;
  endDate?: string;
  startDate?: string;
  /** Walmart is throwing errors because this field is not allowed even though their documentation requires it
   * Keeping it commented out for reference
   */
  // This will be the product type from `CUSTRECORD_VIVO_CNT_WAL_PRDT_TYPE_OO`
  // specProductType: string;
  batteryTechnologyType?: string;
  externalProductIdentifier?: WalmartExternalProductIdentifier[];
  IsPreorder?: "No" | "Yes";
  inventory?: WalmartInventory[];
  MustShipAlone?: "No" | "Yes";
  stateRestrictions?: WalmartStateRestrictions[];
  SkuUpdate?: "No" | "Yes";
  automate_pricing?: WalmartAutomatePricing;
  electronicsIndicator?: "No" | "Yes";
  shipsInOriginalPackaging?: "No" | "Yes";
  msrp?: number;
  product_package_dimensions_and_weight?: WalmartProductPackageDimensionsAndWeight;
  chemicalAerosolPesticide?: "No" | "Yes";
  fulfillmentLagTime?: number;
  releaseDate?: string;
  ProductIdUpdate?: "No" | "Yes";
}

export interface WalmartFullVisible {
  assembledProductLength?: MeasureAndUnit;
  assembledProductWeight?: MeasureAndUnit;
  assembledProductWidth?: MeasureAndUnit;
  assembledProductHeight?: MeasureAndUnit;
  brand?: string;
  certification_type?: string;
  children_product_certificate_document_reference_id?: string;
  children_product_test_report_document_reference_id?: string;
  condition?: string;
  count?: number;
  general_certificate_of_conformity_document_reference_id?: string;
  has_written_warranty?: string;
  isPrimaryVariant?: string;
  isProp65WarningRequired?: string;
  keyFeatures?: string[];
  mainImageUrl?: string;
  manufacturer?: string;
  manufacturerPartNumber?: string;
  modelNumber?: string;
  multipackQuantity?: number;
  netContent?: Record<string, unknown>;
  netContentStatement?: string;
  productName?: string;
  productSecondaryImageURL?: string[];
  prop65WarningText?: string;
  sink_type?: string[];
  leg_type?: string;
  shortDescription?: string;
  swatchImages?: Record<string, unknown>[];
  thirdPartyAccreditationSymbolOnProductPackageCode?: string[];
  variantAttributeNames?: string[];
  variantGroupId?: string;
  warrantyText?: string;
  warrantyURL?: string;
  aaiaBrandID?: string;
  academicInstitution?: string;
  accentColor?: string;
  accessoriesIncluded?: string[];
  acoustic_damper_type?: string;
  activity?: string[];
  adjustable_height?: string;
  adjustable_shelves?: string;
  ageGroup?: string[];
  amps?: Record<string, unknown>;
  animalBreed?: string[];
  animalHealthConcern?: string[];
  animalLifestage?: string[];
  animalType?: string[];
  appliance_type?: string;
  arm_height?: Record<string, unknown>;
  arm_style?: string;
  art_easel_type?: string[];
  aspectRatio?: string;
  assemblyInstructions?: string;
  athlete?: string[];
  attachmentStyle?: string;
  automotivePartsDivision?: string[];
  automotive_safety_part_and_accessory_type?: string[];
  background_color?: string;
  bagCaseFeature?: string[];
  baseColor?: string;
  baseMaterial?: string;
  base_diameter?: Record<string, unknown>;
  base_dimensions?: string;
  base_style?: string;
  batteryCapacity?: Record<string, unknown>;
  batteryLife?: Record<string, unknown>;
  batterySize?: string;
  batteryTechnologyType?: string;
  battery_consumption_type?: string;
  bedSize?: string;
  bee_house_type?: string[];
  bend_angle?: Record<string, unknown>[];
  bicycleType?: string[];
  bicycleWheelDiameter?: Record<string, unknown>;
  bicycle_stand_and_storage_type?: string;
  bodyParts?: string[];
  brightness?: Record<string, unknown>;
  btu?: number;
  cabinet_material?: string;
  cabinet_width?: Record<string, unknown>;
  cableLength?: Record<string, unknown>;
  cable_management_type?: string;
  cable_organizer_type?: string;
  camera_and_camcorder_mount_type?: string;
  capacity?: string;
  carry_on_size?: string;
  carrying_type?: string[];
  caster_mount_method?: string;
  caster_type?: string;
  certificationsAndClaims?: string;
  chair_color?: string[];
  chair_included?: string;
  chair_material?: string;
  character?: string[];
  character_group?: string[];
  chargingTime?: Record<string, unknown>;
  chemicalAerosolPesticide?: string;
  clamp_type?: string;
  cleaningCareAndMaintenance?: string;
  clothingFit?: string;
  clothingSize?: string;
  clothingSizeGroup?: string[];
  clothingStyle?: string[];
  clothing_feature?: string[];
  clothing_leg_bottom_opening_style?: string;
  clothing_occasion?: string[];
  collection?: string;
  color?: string;
  colorCategory?: string[];
  colorTemperature?: Record<string, unknown>[];
  compatibility?: string[];
  compatibleBrands?: string[];
  compatibleCars?: string[];
  compatibleDevices?: string[];
  compatibleModels?: string[];
  compatible_cameras?: string[];
  compatible_electric_vehicles?: string;
  component_options?: string[];
  compositeWoodCertificationCode?: string;
  computer_and_machine_cart_type?: string;
  computer_rack_and_mount_type?: string;
  configuration?: string;
  connections?: string[];
  containerType?: string[];
  cordLength?: Record<string, unknown>;
  cotton_candy_machine_type?: string;
  countPerPack?: number;
  coverageArea?: Record<string, unknown>;
  data_storage?: Record<string, unknown>;
  designer?: string;
  desk_chair_type?: string;
  desk_riser_type?: string;
  desk_shape?: string;
  desk_type?: string;
  desktop_organizer_and_pencil_holder_type?: string[];
  desktop_shelf_length?: Record<string, unknown>;
  diameter?: Record<string, unknown>;
  dimensions?: string;
  display_case_type?: string;
  doorOpeningStyle?: string;
  doorStyle?: string;
  door_material?: string;
  drawer_depth?: Record<string, unknown>;
  drop_length?: Record<string, unknown>;
  edition?: string;
  electronicsIndicator?: string;
  electrical_fuse_type?: string;
  electronics_feature?: string[];
  embellishmentType?: string[];
  ethernet_cable_category?: string;
  exerciseBikeType?: string[];
  exercise_machine_attachment_type?: string;
  expandable?: string;
  extension_size?: Record<string, unknown>;
  eyewearFeature?: string[];
  fabricCareInstructions?: string[];
  fabricContent?: Record<string, unknown>[];
  fabric_construction?: string;
  fastenerType?: string[];
  features?: string[];
  filament_materials_supported?: string[];
  file_cabinet_box_and_cart_type?: string;
  fillMaterial?: string[];
  finish?: string;
  fire_safety_certifications?: string;
  firebox_depth?: Record<string, unknown>;
  firebox_height?: Record<string, unknown>;
  firebox_width?: Record<string, unknown>;
  fireplace_features?: string[];
  fitnessGoal?: string[];
  fixture_finish?: string[];
  food_strainer_and_colander_type?: string;
  form?: string[];
  frameColor?: string;
  frameColorConfiguration?: string[];
  frameMaterial?: string[];
  frontEndPhotoPartner?: string;
  front_wheel_diameter?: Record<string, unknown>;
  garbage_can_and_wastebasket_type?: string;
  gender?: string;
  glass_style?: string[];
  globalBrandLicense?: string[];
  golf_club_organizer_type?: string;
  handleMaterial?: string[];
  handleType?: string;
  handle_style?: string;
  handle_width?: Record<string, unknown>;
  hardwareFinish?: string;
  hardware_bracket_type?: string;
  hardware_hinge_type?: string[];
  hasBrakes?: string;
  has_doors?: string;
  has_fireplace_feature?: string;
  has_hutch?: string;
  has_nrtl_listing_certification?: string;
  has_storage_cabinet?: string;
  healthConcerns?: string[];
  holding_capacity?: string;
  homeDecorStyle?: string[];
  housing_material?: string[];
  hunting_camouflage_accessory_type?: string;
  ib_retail_packaging?: string;
  in_wall_installation_rated?: string;
  inflexKitComponent?: string;
  inputsAndOutputs?: Record<string, unknown>[];
  inseam?: Record<string, unknown>;
  installationType?: string;
  installation_required?: string;
  instructions?: string;
  instrument?: string[];
  interior_color?: string;
  interior_depth?: Record<string, unknown>;
  interior_material?: string;
  internalExternal?: string;
  isAssemblyRequired?: string;
  isBulk?: string;
  isCordless?: string;
  isLightBulbIncluded?: string;
  isMagnetic?: string;
  isRefillable?: string;
  isTsaApproved?: string;
  items_included?: string[];
  jaw_length?: Record<string, unknown>;
  labelImage?: Record<string, unknown>[];
  lamp_style?: string[];
  laptop_bag_and_case_type?: string;
  latch_types?: string[];
  laundry_basket_sorter_and_hamper_type?: string;
  law_label_disclosure?: Record<string, unknown>;
  leatherGrade?: string;
  lectern_type?: string;
  leg_color?: string;
  leg_height?: Record<string, unknown>;
  leg_material?: string;
  lensCoating?: string;
  lensMaterial?: string;
  lensTint?: string;
  lid_style?: string;
  lightBulbType?: string;
  lightOutput?: Record<string, unknown>;
  light_bulb_code?: string;
  liner_included?: string;
  lockType?: string;
  lockingMechanism?: string;
  magnification?: string[];
  material?: string[];
  material_handling_securing_strap_type?: string;
  maximumLoadWeight?: Record<string, unknown>;
  maximumOrderQuantity?: number;
  maximumRecommendedAge?: Record<string, unknown>;
  maximumScreenSize?: Record<string, unknown>;
  maximumTemperature?: Record<string, unknown>;
  maximumWeight?: Record<string, unknown>;
  maximum_coverage_area?: Record<string, unknown>;
  maximum_depth?: Record<string, unknown>;
  maximum_expandable_range?: Record<string, unknown>;
  maximum_height?: Record<string, unknown>;
  maximum_length?: Record<string, unknown>;
  maximum_load_weight_per_shelf?: Record<string, unknown>;
  maximum_number_of_monitors?: number;
  maximum_occupancy?: number;
  maximum_pet_weight?: Record<string, unknown>;
  metal?: string[];
  microphone_stand_and_boom_type?: string;
  minimumOrderQuantity?: number;
  minimumRecommendedAge?: Record<string, unknown>;
  minimumScreenSize?: Record<string, unknown>;
  minimumWeight?: Record<string, unknown>;
  minimum_height?: Record<string, unknown>;
  minimum_seat_height?: Record<string, unknown>;
  modelName?: string;
  monogramLetter?: string;
  mountType?: string[];
  music_stand_type?: string;
  network_cable_type?: string;
  nrtl_information?: Record<string, unknown>[];
  numberOfBatteries?: number;
  numberOfCompartments?: number;
  numberOfDrawers?: number;
  numberOfLightBulbs?: number;
  numberOfLights?: number;
  numberOfOutlets?: number;
  numberOfPanels?: number;
  numberOfSheets?: number;
  numberOfShelves?: number;
  numberOfSteps?: number;
  numberOfWheels?: number;
  number_of_animals?: number;
  number_of_bins?: number;
  number_of_buttons?: number;
  number_of_controllable_devices?: string;
  number_of_devices_held?: number;
  number_of_doors?: number;
  number_of_handles?: number;
  number_of_heat_settings?: number;
  number_of_legs?: number;
  number_of_openings?: number;
  number_of_perches?: number;
  number_of_pockets?: number;
  number_of_positions?: number;
  number_of_programs?: number;
  number_of_resistance_levels?: number;
  number_of_tiers?: number;
  occasion?: string[];
  opening_style?: string;
  operating_type?: string;
  orientation?: string;
  originalNewEquivalentProductIdentifier?: Record<string, unknown>;
  outdoor_canopy_type?: string;
  output_power?: Record<string, unknown>;
  overall_chair_depth?: Record<string, unknown>;
  overall_chair_height?: Record<string, unknown>;
  overall_chair_width?: Record<string, unknown>;
  overall_height?: Record<string, unknown>;
  overbed_table_type?: string;
  panel_material?: string;
  pantLegCut?: string;
  pant_leg_length?: string;
  paperSize?: string[];
  partTerminologyID?: string;
  pattern?: string[];
  pegboard_type?: string;
  petSize?: string[];
  pet_stroller_type?: string;
  photoAccessoryItemSku?: string[];
  photoConfigurationAttributeNames?: string[];
  photoItemStoreUpc?: string;
  photoOrderQuantityTier?: number;
  photoPaperFinishConfiguration?: string[];
  photo_studio_background_type?: string;
  pieceCount?: number;
  pipe_fitting_and_coupler_type?: string;
  plantCategory?: string[];
  plant_cage_type?: string;
  plant_name?: string[];
  plant_stand_and_rack_type?: string;
  platform?: string[];
  playground_climber_type?: string;
  podium_type?: string;
  powerType?: string[];
  power_rating?: Record<string, unknown>;
  productLine?: string[];
  product_multifunction_descriptor?: string;
  programs?: string[];
  projector_bag_and_case_type?: string;
  projector_screen_type?: string;
  rackSize?: string;
  rear_wheel_diameter?: Record<string, unknown>;
  recommendedLocations?: string[];
  recommendedRooms?: string[];
  recommendedSurfaces?: string[];
  recommendedUses?: string[];
  recycledMaterialContent?: Record<string, unknown>[];
  required_storage_condition?: string[];
  resistanceMethod?: string;
  restoredProductIdentifier?: Record<string, unknown>;
  rollLength?: Record<string, unknown>;
  roof_style?: string;
  room_divider_and_panel_screen_type?: string;
  rotation_angle?: Record<string, unknown>;
  rotation_direction?: string;
  rugSize?: string;
  screenSize?: Record<string, unknown>;
  season?: string[];
  seatBackHeight?: Record<string, unknown>;
  seatHeight?: Record<string, unknown>;
  seat_back_height_descriptor?: string;
  seat_back_thickness?: Record<string, unknown>;
  seat_back_width?: Record<string, unknown>;
  seat_color?: string[];
  seat_depth?: Record<string, unknown>;
  seat_material?: string[];
  seat_width?: Record<string, unknown>;
  seatingCapacity?: number;
  series?: string;
  shadeMaterial?: string[];
  shadeStyle?: string;
  shade_color?: string[];
  shape?: string;
  shelfDepth?: Record<string, unknown>;
  shelf_and_shelf_unit_type?: string;
  shelf_material?: string[];
  size?: string;
  sizeDescriptor?: string;
  skinType?: string[];
  smallPartsWarnings?: string[];
  speaker_stand_type?: string;
  sport?: string[];
  sportsLeague?: string[];
  sportsTeam?: string[];
  stackable?: string;
  /**Below is an incorrect type but we just send "None" */
  stateRestrictions?: string;
  state_chemical_disclosure?: string;
  steeringControlType?: string;
  stool_type?: string;
  style?: string[];
  suggested_number_of_people_for_assembly?: number;
  switch_type?: string;
  swivel_angle?: Record<string, unknown>;
  tableHeight?: Record<string, unknown>;
  table_color?: string;
  table_shape?: string[];
  table_top__material?: string[];
  table_top__thickness?: Record<string, unknown>;
  table_top_type?: string;
  targetAudience?: string[];
  technology?: string[];
  text?: string;
  text_color?: string[];
  theme?: string;
  therapeutic_light_box_type?: string[];
  thickness?: Record<string, unknown>;
  tile_type?: string;
  tilt_angle?: Record<string, unknown>;
  title?: string;
  tool_box_and_organizer_type?: string[];
  topFinish?: string;
  topMaterial?: string;
  top_color?: string[];
  top_plate_length?: Record<string, unknown>;
  top_plate_width?: Record<string, unknown>;
  tripod_type?: string;
  tvAndMonitorMountType?: string;
  upholstered?: string;
  vehicleMake?: string[];
  vehicleModel?: string[];
  vehicleType?: string[];
  vehicleYear?: number[];
  vehicle_charging_station_type?: string;
  vehicle_cover_type?: string[];
  vehicle_fitment_type?: string;
  vehicle_mount_location?: string[];
  vesa_mounting_pattern?: string[];
  video_game_accessory_type?: string;
  video_game_chair_type?: string;
  viewing_area?: string;
  volts?: Record<string, unknown>[];
  volumeCapacity?: Record<string, unknown>;
  warningText?: string;
  watts?: Record<string, unknown>;
  weather?: string[];
  weight_range?: string;
  wheelDiameter?: Record<string, unknown>;
  wheelType?: string;
  wheel_material?: string[];
  wheel_tread_width?: Record<string, unknown>;
  wheel_width?: Record<string, unknown>;
  wire_and_cable_organizer_type?: string;
  wireless?: string;
  wirelessTechnologies?: string[];
  wood_tone?: string;
  wood_type?: string[];
  work_safety_eye_protection_type?: string;
  workbench_type?: string;
  workingLoadLimit?: Record<string, unknown>;
  workstation_type?: string[];
  zipperMaterial?: string;
}

export interface WalmartCAFullVisible {
  aaiaBrandID?: string[];
  absorbency?: { en?: string; fr?: string };
  academicInstitution?: { en?: string; fr?: string };
  acceleration?: { en?: string; fr?: string };
  accentColor?: { en?: string; fr?: string };
  accentStone?: string[];
  accessoriesIncluded?: { en?: string; fr?: string }[];
  acRating?: string;
  activeIngredients?: {
    activeIngredientName?: { en?: string; fr?: string };
    activeIngredientPercentage?: number;
  }[];
  activity?: { en?: string; fr?: string }[];
  activityStage?: string[];
  actors?: { en?: string; fr?: string }[];
  additionalBISACSubjectCodes?: string[];
  ageGroup?: string[];
  airDraft?: { measure?: number; unit?: string };
  AirGunPowerType?: string;
  airInlet?: { measure?: number; unit?: string };
  alcoholClassAndType?: { en?: string; fr?: string };
  alcoholContentByVolume?: { en?: string; fr?: string };
  alcoholProof?: { en?: string; fr?: string };
  alphanumericCharacter?: string;
  alternateTitle?: { en?: string; fr?: string }[];
  americanWireGauge?: number;
  ammunitionType?: { en?: string; fr?: string };
  amps?: { measure?: number; unit?: string };
  animalBreed?: { en?: string; fr?: string };
  animalHealthConcern?: { en?: string; fr?: string }[];
  animalLifestage?: { en?: string; fr?: string };
  animalType?: { en?: string; fr?: string };
  arborDiameter?: { measure?: string; unit?: string };
  artist?: { en?: string; fr?: string }[];
  artPaintType?: { en?: string; fr?: string };
  aspectRatio?: string;
  assembledProductHeight?: { measure?: number; unit?: string };
  assembledProductLength?: { measure?: number; unit?: string };
  assembledProductWeight?: { measure?: number; unit?: string };
  assembledProductWidth?: { measure?: number; unit?: string };
  assemblyInstructions?: string;
  athlete?: { en?: string; fr?: string }[];
  attachmentStyle?: { en?: string; fr?: string };
  audioFeatures?: { en?: string; fr?: string }[];
  audioPowerOutput?: { en?: string; fr?: string };
  audioTrackCodec?: { en?: string; fr?: string };
  author?: { en?: string; fr?: string }[];
  autographedBy?: { en?: string; fr?: string };
  automotivePartsDivision?: string[];
  averageAirConsumptionAt90PSI?: { measure?: number; unit?: string };
  averageFuelConsumption?: { measure?: number; unit?: string };
  awardsWon?: { en?: string; fr?: string }[];
  babyCarrierPosition?: { en?: string; fr?: string }[];
  babyCarrierStyle?: { en?: string; fr?: string }[];
  babyClothingSize?: { en?: string; fr?: string };
  babyCribType?: string;
  babyFoodPackaging?: { en?: string; fr?: string };
  babyFoodStage?: { en?: string; fr?: string }[];
  babyFormulaStage?: { en?: string; fr?: string }[];
  babyMonitorType?: { en?: string; fr?: string }[];
  backFinding?: string;
  backlightType?: { en?: string; fr?: string };
  backsetSize?: { measure?: number; unit?: string };
  bagCaseFeature?: { en?: string; fr?: string };
  bagStyle?: string[];
  ballCoreMaterial?: { en?: string; fr?: string }[];
  bandWidth?: { measure?: number; unit?: string };
  barrelLength?: { measure?: number; unit?: string };
  baseColor?: { en?: string; fr?: string };
  baseFinish?: { en?: string; fr?: string };
  baseMaterial?: { en?: string; fr?: string };
  basketballSize?: { en?: string; fr?: string };
  batDrop?: string;
  batteriesRequired?: string;
  batteryCapacity?: { measure?: number; unit?: string };
  batteryLife?: { measure?: number; unit?: string };
  batterySize?: { en?: string; fr?: string };
  beam?: { measure?: number; unit?: string };
  beamAngle?: { measure?: number; unit?: string };
  beamSpread?: { measure?: number; unit?: string };
  bedPillowSize?: { en?: string; fr?: string }[];
  bedSize?: { en?: string; fr?: string };
  bedStyle?: { en?: string; fr?: string };
  beefCut?: { en?: string; fr?: string };
  beltBuckleStyle?: { en?: string; fr?: string };
  beltStyle?: { en?: string; fr?: string }[];
  bicycleFrameSize?: { measure?: number; unit?: string };
  bicycleTireSize?: { en?: string; fr?: string };
  bicycleWheelDiameter?: { measure?: number; unit?: string };
  birthstone?: string;
  bisacSubjectCodes?: string[];
  bladeDiameter?: { measure?: number; unit?: string };
  bladeLength?: { measure?: number; unit?: string };
  bladeShank?: { en?: string; fr?: string };
  bladeType?: { en?: string; fr?: string };
  bladeWidth?: { measure?: number; unit?: string };
  blowsPerMinute?: string;
  bodyJewelryStyle?: { en?: string; fr?: string };
  bodyParts?: { en?: string; fr?: string }[];
  boltLengthYardage?: { measure?: number; unit?: string };
  bookFormat?: string;
  bootShaftCircumference?: { measure?: number; unit?: string }[];
  bootShaftHeight?: { measure?: number; unit?: string }[];
  bootShaftStyle?: { en?: string; fr?: string }[];
  bootShaftWidthStyle?: { en?: string; fr?: string }[];
  boreStroke?: { en?: string; fr?: string };
  braBandSize?: { measure?: number; unit?: string };
  braceletCharmStyle?: { en?: string; fr?: string };
  braceletStyle?: string;
  braCupSize?: { en?: string; fr?: string };
  braSize?: { en?: string; fr?: string };
  braStyle?: { en?: string; fr?: string }[];
  breakingStrength?: { measure?: number; unit?: string };
  brightness?: { measure?: number; unit?: string };
  bristleMaterial?: { en?: string; fr?: string };
  btu?: number;
  cableLength?: { measure?: number; unit?: string };
  caffeineDesignation?: string;
  calendarFormat?: { en?: string; fr?: string };
  calendarTerm?: { measure?: number; unit?: string };
  caliber?: { en?: string; fr?: string };
  calories?: { measure?: number; unit?: string };
  caloriesFromFat?: { measure?: number; unit?: string };
  cameraLensType?: { en?: string; fr?: string };
  candlePower?: { en?: string; fr?: string };
  capacity?: { en?: string; fr?: string }[];
  carats?: { measure?: number; unit?: string };
  carpetStyle?: { en?: string; fr?: string };
  carSeatBaseDepth?: { measure?: number; unit?: string };
  carSeatBaseWidth?: { measure?: number; unit?: string };
  carSeatMaxChildHeight?: { measure?: number; unit?: string };
  carSpeakerSizeClass?: { en?: string; fr?: string }[];
  carSpeakerType?: { en?: string; fr?: string }[];
  casualAndDressShoeType?: { en?: string; fr?: string };
  ceeTier?: string;
  cellPhoneServiceProvider?: { en?: string; fr?: string };
  cellPhoneType?: string;
  cellularNetworkTechnology?: { en?: string; fr?: string };
  certifyingAgent?: { en?: string; fr?: string };
  cfmAt40Psi?: { measure?: number; unit?: string };
  cfmAt90Psi?: { measure?: number; unit?: string };
  chainLength?: { measure?: number; unit?: string };
  chainPattern?: string[];
  character?: { en?: string; fr?: string }[];
  chestSize?: { measure?: number; unit?: string };
  childCarSeatType?: string;
  childWalkingHarnessStyle?: { en?: string; fr?: string };
  chuckSize?: { measure?: string; unit?: string };
  chuckType?: { en?: string; fr?: string };
  claspType?: string[];
  cleaningCareAndMaintenance?: { en?: string; fr?: string };
  cleaningPath?: { measure?: number; unit?: string };
  clearingWidth?: { measure?: number; unit?: string };
  clockNumberType?: string;
  clockWatchFaceColor?: { en?: string; fr?: string };
  clothingCut?: { en?: string; fr?: string }[];
  clothingFit?: { en?: string; fr?: string };
  clothingLengthStyle?: { en?: string; fr?: string };
  clothingSize?: { en?: string; fr?: string };
  clothingSizeGroup?: string;
  clothingStyle?: { en?: string; fr?: string }[];
  clothingTopStyle?: { en?: string; fr?: string }[];
  clothingWeight?: string;
  coldCrankAmp?: number;
  collarType?: { en?: string; fr?: string };
  collection?: { en?: string; fr?: string };
  colletSize?: { measure?: string; unit?: string };
  color?: { en?: string; fr?: string }[];
  colorCategory?: string[];
  colorPagesPerMinute?: number;
  colorTemperature?: { measure?: number; unit?: string };
  compatibleBrands?: { en?: string; fr?: string }[];
  compatibleCars?: { en?: string; fr?: string };
  compatibleConduitSizes?: { measure?: number; unit?: string }[];
  compatibleDevices?: { en?: string; fr?: string }[];
  compatibleModels?: { en?: string; fr?: string }[];
  compatibleTireSize?: string;
  compositeWoodCertificationCode?: string;
  compressionRatio?: string;
  computerStyle?: { en?: string; fr?: string };
  condition?: string;
  conductorMaterial?: { en?: string; fr?: string };
  configuration?: { en?: string; fr?: string };
  connections?: { en?: string; fr?: string }[];
  connectorFinish?: { en?: string; fr?: string };
  constructionType?: { en?: string; fr?: string };
  containerType?: { en?: string; fr?: string }[];
  containsSulfites?: string;
  contaminantsRemoved?: { en?: string; fr?: string };
  coolingSystem?: { en?: string; fr?: string };
  cordLength?: { measure?: number; unit?: string };
  count?: string;
  countPerPack?: number;
  countryOfOriginTextiles?: string;
  coverageArea?: { measure?: number; unit?: string };
  cpuSocketType?: { en?: string; fr?: string }[];
  cuisine?: { en?: string; fr?: string }[];
  curbWeight?: { measure?: number; unit?: string };
  curtainLength?: { measure?: number; unit?: string };
  curtainPanelStyle?: { en?: string; fr?: string };
  cushionColor?: { en?: string; fr?: string };
  cuttingWidth?: { en?: string; fr?: string };
  dataIntegrityCheck?: string;
  dataTransferRate?: { en?: string; fr?: string };
  decibelRating?: { measure?: number; unit?: string };
  defrostType?: { en?: string; fr?: string };
  designer?: { en?: string; fr?: string };
  dexterity?: { en?: string; fr?: string };
  diameter?: { measure?: number; unit?: string };
  diamondClarity?: string;
  diamondColor?: string;
  diamondCut?: string;
  diaperSize?: { en?: string; fr?: string };
  diaposableBabyDiaperType?: { en?: string; fr?: string }[];
  dietaryMethod?: { en?: string; fr?: string }[];
  dietType?: string;
  digitalAudioFileFormat?: { en?: string; fr?: string }[];
  digitalFileFormat?: string[];
  digitalZoom?: string;
  dimensions?: { en?: string; fr?: string };
  dinSize?: { en?: string; fr?: string }[];
  director?: { en?: string; fr?: string };
  discSize?: { measure?: number; unit?: string };
  dishwasherType?: { en?: string; fr?: string };
  displayResolution?: string[];
  displayTechnology?: { en?: string; fr?: string };
  doorOpeningStyle?: { en?: string; fr?: string };
  doorStyle?: { en?: string; fr?: string };
  dosage?: { en?: string; fr?: string };
  draft?: { measure?: number; unit?: string };
  drawerDimensions?: string;
  drawerPosition?: { en?: string; fr?: string };
  dressShirtSize?: string;
  dressStyle?: { en?: string; fr?: string };
  driveSystem?: { en?: string; fr?: string };
  drivetrain?: { en?: string; fr?: string };
  dropDistance?: { en?: string; fr?: string };
  drugActiveInactiveIngredientsImage?: string;
  drugDosageInstructionsImage?: string;
  drumSetCymbalType?: string[];
  dryTime?: { measure?: number; unit?: string };
  dryWeight?: { measure?: number; unit?: string };
  dubbedLanguages?: { en?: string; fr?: string }[];
  duration?: { measure?: number; unit?: string };
  dvdReleaseDate?: string;
  earGaugeSize?: { measure?: number; unit?: string };
  earringStyle?: string;
  edition?: { en?: string; fr?: string };
  editor?: { en?: string; fr?: string };
  educationalFocus?: { en?: string; fr?: string }[];
  electricalBallastFactor?: number;
  embellishmentType?: { en?: string; fr?: string }[];
  energyGuideLabel?: string;
  engineDisplacement?: { measure?: number; unit?: string };
  engineLocation?: { en?: string; fr?: string };
  engineModel?: { en?: string; fr?: string };
  envelopeSize?: { en?: string; fr?: string };
  episode?: { en?: string; fr?: string };
  equalizerControl?: { en?: string; fr?: string };
  esrbRating?: string;
  estimatedEnergyCostPerYear?: { measure?: number; unit?: string };
  exposureModes?: { en?: string; fr?: string }[];
  eyewearFrameSize?: { en?: string; fr?: string };
  eyewearFrameStyle?: { en?: string; fr?: string };
  eyewearLensFeature?: { en?: string; fr?: string }[];
  eyewearRimStyle?: string;
  fabricCareInstructions?: { en?: string; fr?: string }[];
  fabricColor?: { en?: string; fr?: string };
  fabricContent?: {
    materialName?: { en?: string; fr?: string };
    materialPercentage?: number;
  }[];
  fabricPurchaseForm?: string;
  facingDirection?: { en?: string; fr?: string };
  fastenerHeadType?: { en?: string; fr?: string };
  fastenerType?: { en?: string; fr?: string };
  faucetDrillings?: { en?: string; fr?: string };
  faucetHandleDesign?: { en?: string; fr?: string };
  feedingInstructions?: { en?: string; fr?: string };
  fieldOfView?: { en?: string; fr?: string };
  fillMaterial?: { en?: string; fr?: string }[];
  filterLife?: { en?: string; fr?: string };
  fineness?: string;
  finish?: { en?: string; fr?: string };
  firearmAction?: { en?: string; fr?: string };
  firearmChamberLength?: number;
  fireExtinguisherClasses?: string[];
  fishingLinePoundTest?: number;
  fishingLocation?: { en?: string; fr?: string };
  fitnessGoal?: { en?: string; fr?: string };
  fitType?: string;
  flashPoint?: { en?: string; fr?: string };
  flashType?: { en?: string; fr?: string };
  flavor?: { en?: string; fr?: string };
  flooringMaterial?: { en?: string; fr?: string };
  flowRate?: { measure?: number; unit?: string };
  fluidOunces?: { measure?: number; unit?: string };
  fluidOuncesSupplying100Calories?: { measure?: number; unit?: string };
  focalLength?: { measure?: string; unit?: string };
  focalRatio?: string;
  focusType?: { en?: string; fr?: string }[];
  foodAllergenStatements?: { en?: string; fr?: string }[];
  foodForm?: { en?: string; fr?: string };
  foodPreparationTips?: { en?: string; fr?: string }[];
  footballSize?: { en?: string; fr?: string };
  footwearHeelStyle?: { en?: string; fr?: string };
  form?: { en?: string; fr?: string };
  formFactor?: { en?: string; fr?: string };
  forwardFacingMaximumWeight?: { measure?: number; unit?: string };
  forwardFacingMinimumWeight?: { measure?: number; unit?: string };
  frameColor?: { en?: string; fr?: string };
  framed?: { en?: string; fr?: string };
  frameMaterial?: { en?: string; fr?: string }[];
  frontBrakes?: { en?: string; fr?: string };
  frontFacingCameraMegapixels?: { measure?: number; unit?: string };
  frontSuspension?: { en?: string; fr?: string };
  frontTires?: string;
  frontWheels?: { en?: string; fr?: string };
  fuelCapacity?: { measure?: number; unit?: string };
  fuelRequirement?: { en?: string; fr?: string };
  fuelSystem?: { en?: string; fr?: string };
  fuelType?: { en?: string; fr?: string };
  gallonsPerFlush?: { measure?: number; unit?: string };
  gallonsPerMinute?: { measure?: number; unit?: string };
  gemstone?: string;
  gemstoneShape?: string;
  gender?: string;
  giftCardAmount?: number;
  globalBrandLicense?: { en?: string; fr?: string }[];
  golfClubShaftFlex?: { en?: string; fr?: string };
  golfClubShaftType?: { en?: string; fr?: string };
  gotsCertification?: string;
  grade?: { en?: string; fr?: string };
  gramsSquareMeter?: number;
  graphicsInformation?: { en?: string; fr?: string };
  gritSize?: string;
  guitarType?: string;
  hairCareKeyBenefit?: string[];
  hairColorCategory?: string;
  hairLength?: { en?: string; fr?: string }[];
  hairProductForm?: string;
  hairType?: { en?: string; fr?: string };
  handing?: { en?: string; fr?: string };
  handleLength?: { measure?: number; unit?: string };
  handleMaterial?: { en?: string; fr?: string }[];
  handleType?: { en?: string; fr?: string };
  hardDriveCapacity?: { measure?: number; unit?: string };
  hardOrSoftCase?: string;
  hardwareFinish?: { en?: string; fr?: string };
  has3dCapabilities?: string;
  hasAdaptiveLenses?: string;
  hasAutomaticDocumentFeeder?: string;
  hasAutomaticShutoff?: string;
  hasAutomaticTwoSidedPrinting?: string;
  hasBluetooth?: string;
  hasCeeCertification?: string;
  hasCfl?: string;
  hasCharcoalBasket?: string;
  hasDovetailBarSystem?: string;
  hasExpiration?: string;
  hasFlash?: string;
  hasFuelContainer?: string;
  hasGMOs?: string;
  hasHandle?: string;
  hasIngredientList?: string;
  hasIntegratedSpeakers?: string;
  hasLatchSystem?: string;
  hasLcdScreen?: string;
  hasLowEmissivity?: string;
  hasMemoryCardSlot?: string;
  hasNightVision?: string;
  hasParentalAdvisoryLabel?: string;
  hasPricePerUnit?: string;
  hasRadiantHeat?: string;
  hasRedEyeReduction?: string;
  hasRemovableStrap?: string;
  hasSelfTimer?: string;
  hasShoulderStrap?: string;
  hasSideShelf?: string;
  hasSignalBooster?: string;
  hasSubtitles?: string;
  hasTankTray?: string;
  hasTouchscreen?: string;
  hasWarranty?: string;
  hatSize?: string;
  hatStyle?: { en?: string; fr?: string }[];
  hazardousMaterialsInd?: string;
  headboardStyle?: { en?: string; fr?: string };
  headphoneFeatures?: { en?: string; fr?: string }[];
  headphoneStyle?: string;
  healthConcerns?: { en?: string; fr?: string }[];
  heelDrop?: { measure?: number; unit?: string };
  heelHeight?: { measure?: number; unit?: string };
  hitchClass?: { en?: string; fr?: string };
  holeSize?: { measure?: number; unit?: string };
  holidayLightingStyle?: { en?: string; fr?: string }[];
  homeDecorStyle?: { en?: string; fr?: string };
  horsepower?: { measure?: number; unit?: string };
  hosieryStyle?: { en?: string; fr?: string }[];
  hpprintercartridgeNumber?: string[];
  hullLength?: { measure?: number; unit?: string };
  humidificationOutputPerDay?: string;
  iceMakerType?: { en?: string; fr?: string }[];
  illustrator?: { en?: string; fr?: string };
  impactEnergy?: { measure?: number; unit?: string };
  impedance?: string;
  impellerPropeller?: { en?: string; fr?: string };
  inactiveIngredients?: { en?: string; fr?: string }[];
  inDashSystem?: string;
  inductionSafe?: string;
  inductionSystem?: { en?: string; fr?: string };
  inflexKitComponent?: string;
  ingredientListImage?: string;
  ingredientPreference?: string[];
  ingredients?: { en?: string; fr?: string };
  inkColor?: { en?: string; fr?: string }[];
  inputsAndOutputs?: {
    inputOutputType?: { en?: string; fr?: string };
    inputOutputQuantity?: number;
  }[];
  inseam?: { measure?: number; unit?: string };
  installationType?: { en?: string; fr?: string };
  instructions?: { en?: string; fr?: string };
  instrument?: { en?: string; fr?: string }[];
  insulationType?: string;
  interfaceType?: { en?: string; fr?: string }[];
  internalExternal?: string;
  isAdultProduct?: string;
  isAnimated?: string;
  isAntiglare?: string;
  isAntique?: string;
  isAssemblyRequired?: string;
  isBiodegradable?: string;
  "ISBN-13"?: { en?: string; fr?: string }[];
  isBulk?: string;
  isCollectible?: string;
  isCombustible?: string;
  isControlledSubstance?: string;
  isCordless?: string;
  isDarkSkyCompliant?: string;
  isDisposable?: string;
  isDownloadableContentAvailable?: string;
  isDubbed?: string;
  isEdited?: string;
  isElectric?: string;
  isEnergyGuideLabelRequired?: string;
  isEnergyStarCertified?: string;
  isEnhanced?: string;
  isEstateBottled?: string;
  isFairTrade?: string;
  isFastSetting?: string;
  isFireResistant?: string;
  isFlammable?: string;
  isFogResistant?: string;
  isFoldable?: string;
  isHypoallergenic?: string;
  isIndustrial?: string;
  isInflatable?: string;
  isLargePrint?: string;
  isLatexFree?: string;
  isLined?: string;
  isLockable?: string;
  isMadeFromReclaimedMaterials?: string;
  isMadeFromRecycledMaterial?: string;
  isMadeFromSustainableMaterials?: string;
  isMagnetic?: string;
  isMaternity?: string;
  isMemorabilia?: string;
  isMoldResistant?: string;
  isMulticoated?: string;
  isNoncomodegenic?: string;
  isNonGrape?: string;
  isNonStick?: string;
  isNutritionFactsLabelRequired?: string;
  isOdorless?: string;
  isOnlineMultiplayerAvailable?: string;
  isOrthopedic?: string;
  isParfocal?: string;
  isPerishable?: string;
  isPetFriendly?: { en?: string; fr?: string };
  isPolarized?: string;
  isPortable?: string;
  isPowered?: string;
  isPrefinished?: string;
  isPrimaryVariant?: string;
  isRatedForOutdoorUse?: string;
  isReadyToUse?: string;
  isRecyclable?: string;
  isRefillable?: string;
  isReflective?: string;
  isRemoteControlIncluded?: string;
  isResizable?: string;
  isRetractable?: string;
  isReusable?: string;
  isRunFlat?: string;
  isScratchResistant?: string;
  isSelfAdhesive?: string;
  isSelfTanning?: string;
  isSet?: string;
  isSmart?: string;
  isSpaceSaving?: string;
  issue?: { en?: string; fr?: string };
  isTearResistant?: string;
  isTinted?: string;
  isTravelSize?: string;
  isUnabridged?: string;
  isUnscented?: string;
  isWaterproof?: string;
  isWaterResistant?: string;
  isWaterSoluble?: string;
  isWeatherResistant?: string;
  isWheeled?: string;
  jacketStyle?: { en?: string; fr?: string }[];
  jeanFinish?: { en?: string; fr?: string }[];
  jeanStyle?: { en?: string; fr?: string }[];
  jeanWash?: { en?: string; fr?: string };
  jewelrySetting?: string[];
  karaokeMachineType?: string;
  labelImage?: { labelImageContains?: string; labelImageURL?: string }[];
  lampLife?: { measure?: number; unit?: string };
  lampType?: { en?: string; fr?: string }[];
  leatherGrade?: { en?: string; fr?: string };
  legOpeningCut?: string;
  lensCoating?: { en?: string; fr?: string };
  lensDiameter?: { measure?: number; unit?: string };
  lensFilterType?: { en?: string; fr?: string };
  lensMaterial?: { en?: string; fr?: string };
  lensTint?: { en?: string; fr?: string };
  lensType?: { en?: string; fr?: string }[];
  lifespan?: { en?: string; fr?: string };
  lightBulbBaseType?: string;
  lightBulbColor?: { en?: string; fr?: string };
  lightBulbShape?: string;
  lightBulbType?: { en?: string; fr?: string };
  lightingFactsLabel?: string;
  lightOutput?: { measure?: number; unit?: string };
  loadCapacity?: { measure?: number; unit?: string };
  loadPosition?: { en?: string; fr?: string };
  lockingMechanism?: { en?: string; fr?: string };
  lockType?: { en?: string; fr?: string };
  loft?: string;
  luggageStyle?: { en?: string; fr?: string };
  luggageType?: { en?: string; fr?: string };
  magnification?: string;
  makesNoise?: string;
  makeupForm?: string[];
  material?: { en?: string; fr?: string }[];
  mattressFirmness?: { en?: string; fr?: string };
  mattressThickness?: { measure?: number; unit?: string };
  maximumAirPressure?: { measure?: number; unit?: string };
  maximumAperture?: string;
  maximumContrastRatio?: string;
  maximumDocumentSize?: { en?: string; fr?: string };
  maximumEnergySurgeRating?: string;
  maximumEnginePower?: { measure?: number; unit?: string };
  maximumIncline?: number;
  maximumInflationPressure?: { measure?: number; unit?: string };
  maximumJawOpening?: { measure?: number; unit?: string };
  maximumLoadWeight?: { measure?: number; unit?: string };
  maximumMotorSpeed?: { measure?: number; unit?: string };
  maximumPrintResolution?: { measure?: number; unit?: string };
  maximumRange?: { en?: string; fr?: string };
  maximumRecommendedAge?: { measure?: number; unit?: string };
  maximumRoomSize?: { measure?: number; unit?: string };
  maximumScannerResolution?: { measure?: number; unit?: string };
  maximumScreenSize?: { measure?: number; unit?: string };
  maximumShutterSpeed?: { measure?: string; unit?: string };
  maximumTemperature?: { measure?: number; unit?: string };
  maximumWattsOut?: { measure?: number; unit?: string };
  maximumWeight?: { measure?: number; unit?: string };
  meal?: { en?: string; fr?: string };
  mealStyle?: { en?: string; fr?: string };
  medicineStrength?: { en?: string; fr?: string };
  memoryCardType?: { en?: string; fr?: string }[];
  mervRating?: string;
  metal?: string;
  metalPurity?: { en?: string; fr?: string };
  microphoneIncluded?: string;
  microphoneTechnology?: { en?: string; fr?: string };
  microwaveOvenType?: { en?: string; fr?: string };
  minimumAperture?: string;
  minimumClearance?: { measure?: number; unit?: string };
  minimumRecommendedAge?: { measure?: number; unit?: string };
  minimumScreenSize?: { measure?: number; unit?: string };
  minimumShutterSpeed?: { measure?: string; unit?: string };
  minimumTemperature?: { measure?: number; unit?: string };
  minimumWeight?: { measure?: number; unit?: string };
  mobileOperatingSystem?: { en?: string; fr?: string }[];
  modelName?: { en?: string; fr?: string };
  modelNumber?: string;
  monochromeColor?: string;
  monochromePagesPerMinute?: number;
  monogramLetter?: { en?: string; fr?: string };
  motherboardFormFactor?: { en?: string; fr?: string }[];
  motorOilViscosity?: { en?: string; fr?: string };
  mountingPattern?: { en?: string; fr?: string };
  mountType?: { en?: string; fr?: string }[];
  movementDetection?: { en?: string; fr?: string };
  movieGenre?: { en?: string; fr?: string };
  movieSubgenre?: { en?: string; fr?: string };
  mpaaRating?: string;
  mudAndSnowRated?: string;
  multipackQuantity?: number;
  musicalInstrumentFamily?: { en?: string; fr?: string };
  musicGenre?: { en?: string; fr?: string };
  musicProducer?: { en?: string; fr?: string };
  musicReleaseType?: { en?: string; fr?: string };
  musicSubGenre?: { en?: string; fr?: string };
  nationalDrugCode?: string;
  nativeResolution?: string;
  necklaceStyle?: string;
  neckSize?: { measure?: number; unit?: string };
  noLoadSpeed?: { measure?: number; unit?: string };
  numberInSeries?: string;
  numberOfBins?: string;
  numberOfBlades?: number;
  numberOfBurners?: number;
  numberOfChannels?: string;
  numberOfCompartments?: number;
  numberOfDiscs?: number;
  numberOfDoors?: string;
  numberOfDrawers?: number;
  numberOfEpisodes?: number;
  numberOfGangs?: number;
  numberOfGemstones?: number;
  numberOfHooks?: number;
  numberOfKeys?: number;
  numberOfLights?: number;
  numberOfMegapixels?: { measure?: number; unit?: string };
  numberOfOutlets?: number;
  numberOfPages?: number;
  numberOfPanels?: number;
  numberOfPlayers?: {
    minimumNumberOfPlayers?: number;
    maximumNumberOfPlayers?: number;
  };
  numberOfPoints?: number;
  numberOfPoles?: number;
  numberOfSheets?: number;
  numberOfShelves?: number;
  numberOfSpeakers?: number;
  numberOfSpeeds?: number;
  numberOfSpokes?: number;
  numberOfSteps?: number;
  numberOfStrings?: number;
  numberOfTracks?: number;
  numberOfTwistedPairsPerCable?: number;
  numberOfUsers?: number;
  numberOfWheels?: number;
  nutrientContentClaims?: string[];
  nutrientFootnote?: { en?: string; fr?: string };
  nutrients?: {
    nutrientName?: string;
    nutrientAmount?: string;
    nutrientPercentageDailyValue?: string;
  }[];
  nutritionFactsLabel?: string;
  nutritionIngredientsImage?: string;
  occasion?: { en?: string; fr?: string }[];
  openDoorDimensions?: string;
  operatingSystem?: { en?: string; fr?: string }[];
  operatingTemperature?: { measure?: number; unit?: string };
  opticalDrive?: { en?: string; fr?: string };
  opticalZoom?: string;
  orientation?: string;
  originalLanguages?: { en?: string; fr?: string }[];
  originalNewEquivalentProductIdentifier?: {
    originalProductIdType?: string;
    originalProductId?: string;
  };
  outerwearCoatJacketAnVestType?: { en?: string; fr?: string };
  overallDiameter?: { measure?: number; unit?: string };
  overallExpansion?: { measure?: number; unit?: string };
  paintFinish?: { en?: string; fr?: string };
  pajamaType?: { en?: string; fr?: string };
  pantFit?: { en?: string; fr?: string }[];
  pantLegCut?: string;
  pantRise?: { en?: string; fr?: string };
  pantSize?: string;
  pantStyle?: { en?: string; fr?: string };
  pantySize?: string;
  pantyStyle?: { en?: string; fr?: string };
  paperClipSize?: string;
  paperSize?: { en?: string; fr?: string }[];
  parentalAdvisoryLabelURL?: { en?: string; fr?: string }[];
  partTerminologyID?: string[];
  pattern?: { en?: string; fr?: string }[];
  peakAudioPowerCapacity?: { measure?: number; unit?: string };
  pearlType?: { en?: string; fr?: string }[];
  peiRating?: string;
  pencilLeadDiameter?: string;
  penPointSize?: { measure?: number; unit?: string };
  percentage_of_neutral_spirits?: string;
  percussionInstrumentType?: { en?: string; fr?: string }[];
  performer?: { en?: string; fr?: string }[];
  perfumeCologneType?: string;
  personalRelationship?: { en?: string; fr?: string }[];
  petFoodForm?: { en?: string; fr?: string };
  petSize?: { en?: string; fr?: string };
  physicalMediaFormat?: string[];
  pieceCount?: number;
  pileHeight?: { measure?: number; unit?: string };
  pintsOfMoistureRemovedPerDay?: number;
  plantCategory?: { en?: string; fr?: string };
  platform?: { en?: string; fr?: string };
  plating?: { en?: string; fr?: string };
  poultryCut?: { en?: string; fr?: string };
  powertrain?: { en?: string; fr?: string };
  powerType?: { en?: string; fr?: string };
  precutFabricSpecialtySize?: string;
  pricePerUnitQuantity?: number;
  pricePerUnitUom?: { en?: string; fr?: string };
  primaryIngredient?: { en?: string; fr?: string }[];
  printingTechnology?: { en?: string; fr?: string };
  processorSpeed?: { measure?: number; unit?: string };
  processorType?: { en?: string; fr?: string }[];
  ProductIdUpdate?: string;
  productLine?: { en?: string; fr?: string }[];
  productVolume?: { en?: string; fr?: string };
  propulsionSystem?: { en?: string; fr?: string };
  publicationDate?: string;
  publisher?: { en?: string; fr?: string };
  puffedSnackType?: string;
  pumpIncluded?: string;
  rackSize?: { en?: string; fr?: string };
  RAIDlevel?: string;
  ramMemory?: { measure?: number; unit?: string };
  RAMSpeed?: string;
  rangeAndCooktopBurnerType?: { en?: string; fr?: string };
  ratingReason?: { en?: string; fr?: string };
  readingLevel?: { en?: string; fr?: string };
  rearBrakes?: { en?: string; fr?: string };
  rearCameraMegapixels?: { measure?: number; unit?: string };
  rearFacingMaximumWeight?: { measure?: number; unit?: string };
  rearFacingMinimumWeight?: { measure?: number; unit?: string };
  rearSuspension?: { en?: string; fr?: string };
  rearTires?: string;
  rearWheels?: { en?: string; fr?: string };
  receiverCompatibility?: { measure?: number; unit?: string };
  recommendedLocations?: { en?: string; fr?: string }[];
  recommendedRooms?: { en?: string; fr?: string }[];
  recommendedSurfaces?: { en?: string; fr?: string }[];
  recommendedUses?: { en?: string; fr?: string }[];
  recordableMediaFormats?: { en?: string; fr?: string }[];
  recordLabel?: { en?: string; fr?: string };
  recycledMaterialContent?: {
    recycledMaterial?: string;
    percentageOfRecycledMaterial?: number;
  }[];
  refreshRate?: { measure?: number; unit?: string };
  refrigeratorType?: { en?: string; fr?: string };
  releaseDate?: string;
  religion?: string;
  removeVariantGroup?: string;
  requiredPeripherals?: { en?: string; fr?: string };
  reserveCapacity?: { measure?: number; unit?: string };
  resolution?: { en?: string; fr?: string };
  responseTime?: { measure?: number; unit?: string };
  ringSize?: number;
  ringStyle?: { en?: string; fr?: string }[];
  rollLength?: { measure?: number; unit?: string };
  roughInDistance?: { measure?: string; unit?: string };
  rugSize?: { en?: string; fr?: string };
  rugStyle?: { en?: string; fr?: string }[];
  runTime?: { measure?: number; unit?: string };
  rValue?: number;
  saeDotCompliant?: string;
  safeHandlingInstructions?: { en?: string; fr?: string };
  safetyHarnessStyle?: string;
  sandingBeltSize?: string;
  sandingSpeed?: { measure?: number; unit?: string };
  saxophoneType?: string;
  scarfStyle?: { en?: string; fr?: string }[];
  scent?: { en?: string; fr?: string };
  screenSize?: { measure?: number; unit?: string };
  screenwriter?: { en?: string; fr?: string };
  season?: { en?: string; fr?: string }[];
  seasonCode?: string;
  seasonYear?: number;
  seatBackHeight?: { measure?: number; unit?: string };
  seatBackStyle?: { en?: string; fr?: string };
  seatHeight?: { measure?: number; unit?: string };
  seatingCapacity?: number;
  seatMaterial?: { en?: string; fr?: string };
  secondaryMaterial?: { en?: string; fr?: string }[];
  secondaryStoneType?: string;
  selfTimerDelay?: { en?: string; fr?: string }[];
  sensorResolution?: { en?: string; fr?: string };
  seriesTitle?: { en?: string; fr?: string };
  serviceCount?: number;
  servingSize?: { en?: string; fr?: string };
  servingsPerContainer?: number;
  sewingKitType?: string;
  shackleClearance?: { measure?: number; unit?: string };
  shackleDiameter?: { measure?: number; unit?: string };
  shackleLength?: { measure?: number; unit?: string };
  shadeMaterial?: { en?: string; fr?: string };
  shadeStyle?: { en?: string; fr?: string };
  shaftLength?: string;
  shaftMaterial?: { en?: string; fr?: string }[];
  shankLength?: { measure?: number; unit?: string };
  shankSize?: { measure?: number; unit?: string };
  shape?: { en?: string; fr?: string };
  shearStrength?: { measure?: number; unit?: string };
  shelfDepth?: { measure?: number; unit?: string };
  shelfLife?: { measure?: number; unit?: string };
  shelfStyle?: { en?: string; fr?: string };
  shirtNeckStyle?: { en?: string; fr?: string };
  shoeCategory?: string;
  shoeClosure?: { en?: string; fr?: string };
  shoeSize?: { en?: string; fr?: string };
  shoeSizeSystem?: string;
  shoeSoleMaterial?: { en?: string; fr?: string };
  shoeStyle?: { en?: string; fr?: string };
  shoeWidth?: { en?: string; fr?: string };
  shootingMode?: { en?: string; fr?: string };
  shortsStyle?: { en?: string; fr?: string }[];
  shotgunGauge?: number;
  shredderCutStyles?: { en?: string; fr?: string };
  sideBurnerSize?: { measure?: number; unit?: string };
  size?: { en?: string; fr?: string };
  sizePerPearl?: { measure?: number; unit?: string };
  skillLevel?: { en?: string; fr?: string };
  skinCareConcern?: { en?: string; fr?: string }[];
  skinTone?: { en?: string; fr?: string };
  skinType?: { en?: string; fr?: string };
  skirtAndDressCut?: { en?: string; fr?: string }[];
  skirtLength?: { measure?: number; unit?: string };
  skirtLengthStyle?: { en?: string; fr?: string };
  slatWidth?: { measure?: number; unit?: string };
  sleepingBagSize?: { en?: string; fr?: string };
  sleeveLength?: { measure?: number; unit?: string };
  sleeveLengthStyle?: string;
  sleeveStyle?: { en?: string; fr?: string };
  smallPartsWarnings?: string[];
  snowLoadRating?: { measure?: number; unit?: string };
  soccerBallSize?: string;
  socketDepth?: string;
  sockRise?: string;
  sockSize?: string;
  sockStyle?: { en?: string; fr?: string };
  softwareCategory?: { en?: string; fr?: string }[];
  songwriter?: { en?: string; fr?: string };
  soundKey?: string[];
  spfValue?: number;
  spiceLevel?: { en?: string; fr?: string };
  spindleThread?: { en?: string; fr?: string };
  sport?: { en?: string; fr?: string }[];
  sportsLeague?: { en?: string; fr?: string }[];
  sportsTeam?: { en?: string; fr?: string }[];
  sprayPatterns?: { en?: string; fr?: string };
  squareDriveSize?: string;
  standbyTime?: { measure?: number; unit?: string };
  stoneCreationMethod?: { en?: string; fr?: string };
  stoneTreatment?: { en?: string; fr?: string };
  stopUseIndications?: { en?: string; fr?: string }[];
  streamingServices?: { en?: string; fr?: string };
  strideLength?: number;
  strokeLength?: { measure?: number; unit?: string };
  strokesPerMinute?: string;
  strollerType?: { en?: string; fr?: string }[];
  studioProductionCompany?: { en?: string; fr?: string };
  style?: { en?: string; fr?: string };
  submodel?: { en?: string; fr?: string };
  subtitledLanguages?: { en?: string; fr?: string }[];
  sugarPerServing?: number;
  suitBreastingStyle?: string;
  sunglassesStyle?: { en?: string; fr?: string };
  supplementActiveInactiveIngredientsImage?: string;
  supplementDosageInstructionsImage?: string;
  supplementFactsLabel?: string;
  swatchImages?: { swatchVariantAttribute?: string; swatchImageUrl?: string }[];
  sweaterStyle?: { en?: string; fr?: string }[];
  sweingMachineType?: string;
  swimsuitStyle?: { en?: string; fr?: string };
  symptoms?: { en?: string; fr?: string };
  synopsis?: { en?: string; fr?: string };
  systemOfMeasurement?: { en?: string; fr?: string };
  systemRequirements?: { en?: string; fr?: string }[];
  tabColor?: { en?: string; fr?: string };
  tabCut?: string;
  tableHeight?: { measure?: number; unit?: string };
  talkTime?: { measure?: number; unit?: string };
  tankConfiguration?: { en?: string; fr?: string };
  targetAudience?: { en?: string; fr?: string }[];
  teethPerInch?: number;
  televisionType?: { en?: string; fr?: string }[];
  tentType?: { en?: string; fr?: string };
  theatricalReleaseDate?: string;
  theme?: { en?: string; fr?: string }[];
  thickness?: { measure?: number; unit?: string };
  threadCount?: number;
  threadStandard?: { en?: string; fr?: string };
  throwRatio?: string;
  thrust?: { measure?: number; unit?: string };
  tightsSheerness?: string;
  timeAged?: { measure?: number; unit?: string };
  tireAspectRatio?: number;
  tireDiameter?: { measure?: number; unit?: string };
  tireLoadIndex?: number;
  tireLoadRange?: string;
  tireSeason?: { en?: string; fr?: string };
  tireSidewallStyle?: { en?: string; fr?: string };
  tireSize?: string;
  tireSpeedRating?: { en?: string; fr?: string };
  tireTemperatureRating?: string;
  tireTractionRating?: string;
  tireTreadwearRating?: number;
  tireType?: { en?: string; fr?: string };
  tireWidth?: number;
  title?: { en?: string; fr?: string };
  toeStyle?: { en?: string; fr?: string };
  topDimensions?: { en?: string; fr?: string };
  topFinish?: { en?: string; fr?: string };
  topMaterial?: { en?: string; fr?: string };
  topSpeed?: { measure?: number; unit?: string };
  torque?: string;
  totalCarbohydrate?: { measure?: number; unit?: string };
  totalCarbohydratePercentageDailyValue?: number;
  totalCookingArea?: { measure?: number; unit?: string };
  totalDiamondWeight?: { measure?: number; unit?: string };
  totalFat?: { measure?: number; unit?: string };
  totalFatPercentageDailyValue?: number;
  totalProtein?: { measure?: number; unit?: string };
  totalProteinPercentageDailyValue?: number;
  towingCapacity?: { measure?: number; unit?: string };
  trackListings?: {
    trackNumber?: number;
    trackName?: string;
    trackDuration?: string;
  }[];
  translatedFrom?: { en?: string; fr?: string };
  translator?: { en?: string; fr?: string };
  transmissionDesignation?: { en?: string; fr?: string };
  travelSystemCompatibility?: { en?: string; fr?: string };
  treadDepth?: { measure?: string; unit?: string };
  treadWidth?: { measure?: string; unit?: string };
  tShirtType?: { en?: string; fr?: string }[];
  tvAndMonitorMountType?: { en?: string; fr?: string };
  tvNetwork?: { en?: string; fr?: string };
  tvRating?: { en?: string; fr?: string };
  tvShowGenre?: { en?: string; fr?: string };
  tvShowSeason?: string;
  tvShowSubgenre?: { en?: string; fr?: string };
  underpantsType?: { en?: string; fr?: string };
  underwearStyle?: { en?: string; fr?: string }[];
  uniformTireQualityGrade?: { en?: string; fr?: string };
  unitsPerConsumerUnit?: number;
  upperBodyStrapConfiguration?: { en?: string; fr?: string }[];
  uvRating?: number;
  variantAttributeNames?: string[];
  variantGroupId?: string;
  vaseIncluded?: string;
  vehicleClassDesignator?: { en?: string; fr?: string };
  vehicleMake?: { en?: string; fr?: string };
  vehicleModel?: { en?: string; fr?: string };
  vehicleRimSize?: { en?: string; fr?: string };
  vehicleType?: { en?: string; fr?: string };
  vehicleYear?: number;
  velocity?: { measure?: number; unit?: string };
  version?: string;
  videoGameCollection?: { en?: string; fr?: string };
  videoGameGenre?: string[];
  vintage?: number;
  vocLevel?: string;
  volts?: { measure?: number; unit?: string }[];
  volumeCapacity?: { measure?: number; unit?: string };
  waistSize?: { measure?: number; unit?: string };
  waistStyle?: string[];
  wallOvenType?: { en?: string; fr?: string };
  washingMachineType?: { en?: string; fr?: string };
  watchBandColor?: { en?: string; fr?: string };
  watchBandLength?: { measure?: number; unit?: string };
  watchBandMaterial?: string[];
  watchBezelMaterial?: { en?: string; fr?: string }[];
  watchCaseMaterial?: string;
  watchCaseShape?: string;
  watchCaseSize?: { measure?: number; unit?: string };
  watchCaseThickness?: { measure?: string; unit?: string };
  watchComplication?: { en?: string; fr?: string };
  watchCrystalMaterial?: string[];
  watchMovement?: string;
  watchMovementType?: string[];
  watchStyle?: { en?: string; fr?: string }[];
  waterCapacity?: { measure?: number; unit?: string };
  watts?: { measure?: number; unit?: string };
  weather?: { en?: string; fr?: string }[];
  wheelbase?: { measure?: number; unit?: string };
  wheelDiameter?: { measure?: number; unit?: string };
  wigCapStyle?: string;
  wigStyles?: { en?: string; fr?: string }[];
  windowTreatmentSheerness?: string[];
  wineAppellation?: { en?: string; fr?: string };
  wineVarietal?: { en?: string; fr?: string };
  wirelessTechnologies?: { en?: string; fr?: string }[];
  workingLoadLimit?: number;
  workingPressure?: { measure?: number; unit?: string };
  year?: number;
  zipperMaterial?: { en?: string; fr?: string };
}

export type WalmartCAVisible = WalmartCAFullVisible;

// --- Walmart Canada MP_ITEM_INTL types ---
// Used for NEW items on Walmart CA. Full content feed with bilingual (en/fr) orderable fields.

export interface CABilingual {
  en: string;
  fr?: string;
}

export interface WalmartCAIntlOrderable {
  sku: string;
  productIdentifiers: {
    productIdType: "UPC" | "GTIN" | "ISBN" | "EAN";
    productId: string;
  };
  productName: CABilingual;
  brand: CABilingual;
  price: number;
  ShippingWeight: { measure: number; unit: "lb" };
  productTaxCode?: number;
  countryOfOriginAssembly?: string[];
  hsCode?: string;
  startDate?: string;
  endDate?: string;
  keyFeatures?: CABilingual[];
  features?: CABilingual[];
  shortDescription?: CABilingual;
  manufacturer?: CABilingual;
  manufacturerPartNumber?: string;
  mainImageUrl?: string;
  productSecondaryImageURL?: string[];
  warrantyText?: CABilingual;
  warrantyURL?: string;
  electronicsIndicator?: "Yes" | "No";
  batteryTechnologyType?: string;
  msrp?: number;
  MustShipAlone?: "Yes" | "No";
  shipsInOriginalPackaging?: "Yes" | "No";
  keywords?: string;
  smallPartsWarnings?: string[];
}

export interface MpItemIntl {
  Orderable: WalmartCAIntlOrderable;
  Visible: Record<string, WalmartCAVisible>;
}

export interface MpItemIntlFeedHeader {
  processMode: "REPLACE";
  subset: "EXTERNAL";
  sellingChannel: "marketplace";
  mart: "WALMART_CA";
  locale: ("en" | "fr")[];
  version: "3.16";
}

export interface MpItemIntlFeed {
  MPItemFeedHeader: MpItemIntlFeedHeader;
  MPItem: MpItemIntl[];
}
